# Site settings
title: BinaryBlog
description: > # this means to ignore newlines until "baseurl:"
    A blog to log and remember programming things.  
baseurl: "/blog" # the subpath of your site, e.g. /blog/
port: 80
url: "http://www.binarybox.ch" # the base hostname & protocol for your site
github_username: jduc
timezone: "Europe/Zurich"
safe: true
lsi: false
source: /home/wes/binaryblog/

# Build settings
markdown: kramdown
