# Site settings
title: BinaryBlog
description: > # this means to ignore newlines until "baseurl:"
    A blog to log and remember programming things.  
baseurl: /binaryblog
github_username: jduc
timezone: "Europe/Zurich"

# Build settings
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from

theme: jekyll-theme-slate