# Site settings
title: BinaryBlog
description: > # this means to ignore newlines until "baseurl:"
    A blog to log and remember programming things.  
github_username: jduc
timezone: "Europe/Zurich"
safe: true
lsi: false
#source: /home/wes/binaryblog/

# Build settings
markdown: kramdown
